
services:
  mongodb:
    container_name: mongodb-servicos
    image: mongo:8
    volumes:
      - vol-mongodb-servicos:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - servicos-network

  mailsender:
    container_name: mailsender-servicos
    image: ruanlopes1350/mailsender:latest
    ports:
      - 5016:5016
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - servicos-network
  
  api:
    container_name: api-servicos
    build: ./
    environment:
      - DB_URL=mongodb://mongodb-servicos:27017/servicosPublicos
      - NODE_ENV=production
    ports:
      - 5011:5011
    env_file:
      - ./.env
    depends_on:
      mongodb:
        condition: service_healthy
      mailsender:
        condition: service_started
    networks:
      - servicos-network
    restart: unless-stopped

volumes:
  vol-mongodb-servicos:

networks:
  servicos-network:
    name: servicos-network
    driver: bridge